apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-call-center-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: temporal-call-center-ui
  template:
    metadata:
      labels:
        app: temporal-call-center-ui
    spec:
      containers:
      - name: workflow
        image: ktenzer/temporal-call-center-ui:v1.0
        imagePullPolicy: Always
        ports:
        - name: ui
          containerPort: 5000
        env:
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              key: TWILIO_ACCOUNT_SID
              name: twilio-secret
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: TWILIO_AUTH_TOKEN
              name: twilio-secret
        - name: TWILIO_API_KEY
          valueFrom:
            secretKeyRef:
              key: TWILIO_API_KEY
              name: twilio-secret
        - name: TWILIO_API_KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: TWILIO_API_KEY_SECRET
              name: twilio-secret
        - name: TEMPORAL_HOST_URL
          value: temporal-call-center.sdvdw.tmprl.cloud:7233
        - name: TEMPORAL_NAMESPACE
          value: temporal-call-center.sdvdw
        - name: TEMPORAL_TASK_QUEUE
          value: twilio
        - name: TEMPORAL_MTLS_TLS_CERT
          value: /etc/certs/tls.crt
        - name: TEMPORAL_MTLS_TLS_KEY
          value: /etc/certs/tls.key
        volumeMounts:
        - mountPath: /etc/certs
          name: certs
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: temporal-call-center-tls
